const list = [
  {
    id: 1,
    title: "Червячки",
    price: 75,
    img: "https://marmeladland.com/assets/images/products/468/svetlyachki.jpg",
    amount: 1,
    description: "Яркий фигурный мармелад в обсыпке, обладающий сочным фруктовым вкусом, который понравится каждому любителю сладкого. ",
    rating: 0, 
  },
  {
    id: 2,
    title:  "Кока Кола",
    price: 85,
    img: "https://marmeladland.com/assets/images/products/544/%E2%95%A8%E2%96%92%E2%95%A4g%E2%95%A4v%E2%95%A4l%E2%95%A8%E2%95%97%E2%95%A8%E2%95%9B%E2%95%A4z%E2%95%A8%E2%95%91%E2%95%A8%E2%95%95-%E2%95%A8%E2%95%91%E2%95%A8%E2%95%9B%E2%95%A8%E2%95%97%E2%95%A8%E2%96%91-%E2%95%A4b-%E2%95%A8%E2%95%9C%E2%95%A8%E2%96%91%E2%95%A4z%E2%95%A8%E2%95%95%E2%95%A8%E2%95%9C%E2%95%A8%E2%95%91%E2%95%A8%E2%95%9B%E2%95%A8%E2%95%95%E2%95%A0zh-a5.jpg",
    amount: 1,
    description: "Всем хорошо знакомы классические мармеладки в виде бутылочк колы в отличие от них, «кола с начинкой» предлагает небольшое дополнение — нежную начинку, которая делает лакомство более интересным и необычным.",
    rating: 0, 
  },
  {
    id: 3,
    title:  "Суфле",
    price: 100,
    img: "https://marmeladland.com/assets/images/products/548/zefirnyie-trubochki-a5.jpg",
    amount: 1,
    description: "Мармеладные суфле производства испанской компании Vidal Привлекают внимание воздушностью, нежным вкусом и мягкими цветами.",
    rating: 0, 
  },
  {
    id: 4,
    title: "Клубничное драже",
    price: 50,
    img: "https://marmeladland.com/assets/images/products/456/klubnichnoe-drazhe.jpg",
    amount: 1,
    description: "Взрослые также оценят оригинальный дизайн мармелада и многообразие форм и цветов лакомства Купить продукцию компании можно оптом на нашем сайте, где представлена широкая линейка продукции фирмы Continental Confectionery Company.",
    rating: 0, 
  },
  {
    id: 5,
    title:  "Персиковые колечки",
    price: 75,
    img: "https://marmeladland.com/assets/images/products/571/persikovyie-a5.jpg",
    amount: 1,
    description: "Персиковые кольца Fini- классика среди кондитерских изделий Популярные кольца сделаны из восхитительно мягкой фруктовой жевательной резинки и сахарной пены, чтобы подарить вам особое удовольствие.",
    rating: 0, 
  },
  {
    id: 6,
    title:  "Жевательные перчики",
    price: 100,
    img: "https://marmeladland.com/assets/images/products/692/gigantskij-perchik.jpg",
    amount: 1,
    description: "Это вкуснейшая сладость, которая станет отличным дополнением к любому чаепитию. Он производится из натуральных ингредиентов и не содержит искусственных красителей и консервантов Каждый кусочек мармелада обладает ярким фруктовым вкусом с легкой остринкой, которая не оставит равнодушным ни одного любителя сладостей.",
    rating: 0, 
  },
];

export default list;
